---
- hosts: localhost
  gather_facts: yes
  become: yes
  tasks:
    - name: Update Debian
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Update RedHat
      ansible.builtin.yum:
        update_cache: yes
      when: ansible_os_family == 'RedHat'

    - ansible.builtin.package:
        name:
          - wrk
        state: present

- hosts: master
  tasks:
    - name: remove whoami service
      command: "docker service rm whoami"
      become: yes
      ignore_errors: True

    - name: create whoami service
      command: "docker service create --name whoami --publish published=8080,target=80 --replicas 1 containous/whoami"
      become: yes


- hosts: localhost
  gather_facts: yes
  tasks:
    - name: wrk 1
      command: "wrk -t4 -c5 -d30s http://{{ hostvars | first }}:8080"
      register: wrk_output

    - name:
      ansible.builtin.debug:
        msg: '{{ wrk_output.stdout_lines | select("search", "Req/Sec") }}'

#scale 2
- hosts: master
  tasks:
    - name: remove whoami service
      command: "docker service rm whoami"
      become: yes
      ignore_errors: True

    - name: create whoami service
      command: "docker service create --name whoami --publish published=8080,target=80 --replicas 2 containous/whoami"
      become: yes


- hosts: localhost
  gather_facts: yes
  tasks:
    - name: wrk 2
      command: "wrk -t4 -c5 -d30s http://{{ hostvars | first }}:8080"
      register: wrk_output2

    - name:
      ansible.builtin.debug:
        msg: '{{ wrk_output2.stdout_lines | select("search", "Req/Sec") }}'

#scale4
- hosts: master
  tasks:
    - name: remove whoami service
      command: "docker service rm whoami"
      become: yes
      ignore_errors: True

    - name: create whoami service
      command: "docker service create --name whoami --publish published=8080,target=80 --replicas 4 containous/whoami"
      become: yes


- hosts: localhost
  gather_facts: yes
  tasks:
    - name: wrk 4
      command: "wrk -t4 -c5 -d30s http://{{ hostvars | first }}:8080"
      register: wrk_output4

    - name:
      ansible.builtin.debug:
        msg: '{{ wrk_output4.stdout_lines | select("search", "Req/Sec") }}'

#scale8
- hosts: master
  tasks:
    - name: remove whoami service
      command: "docker service rm whoami"
      become: yes
      ignore_errors: True

    - name: create whoami service
      command: "docker service create --name whoami --publish published=8080,target=80 --replicas 8 containous/whoami"
      become: yes


- hosts: localhost
  gather_facts: yes
  tasks:
    - name: wrk 8
      command: "wrk -t4 -c5 -d30s http://{{ hostvars | first }}:8080"
      register: wrk_output8

    - name:
      ansible.builtin.debug:
        msg: '{{ wrk_output8.stdout_lines | select("search", "Req/Sec") }}'